services:
  # 1. BASE DE DONNÉES (Warehouse + App DBs)
  postgres:
    image: postgres:15-alpine
    container_name: warehouse_db
    environment:
      POSTGRES_USER: etudiant
      POSTGRES_PASSWORD: data_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - data_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etudiant"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. ORCHESTRATEUR (Airflow avec correctif Protobuf)
  airflow:
    build: .
    container_name: airflow_scheduler
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://etudiant:data_password@postgres:5432/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: 300
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db migrate && 
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true && 
      exec airflow standalone"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt_project:/opt/airflow/dbt_project
      - ./data:/opt/airflow/data
    networks:
      - data_network

  # 3. VISUALISATION (Metabase - Configuré pour durer)
  metabase:
    image: metabase/metabase:latest
    container_name: metabase_bi
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_app
      MB_DB_PORT: 5432
      MB_DB_USER: etudiant
      MB_DB_PASS: data_password
      MB_DB_HOST: postgres
    networks:
      - data_network
    depends_on:
      postgres:
        condition: service_healthy

  # 4. EXPLORATEUR SQL (Adminer)
  adminer:
    image: adminer
    container_name: db_admin_ui
    ports:
      - "8081:8080"
    networks:
      - data_network

networks:
  data_network:
    driver: bridge

volumes:
  pg_data: